In [6]:
#Task 1
import pandas as pd
#Основы чтения и записи данных:
df = pd.read_csv("Таблица для ДЗ.csv")
df.head(10).to_excel("Таблица для ДЗ.xlsx", sheet_name = 'sheet1')

#Работа с DataFrame:
new_df = df[df["Product"] == "Product A"]
new_df[new_df["Customer_Age"] > 50]

#Фильтрация и выбор данных:
df[df["Customer_Rating"] == 5]
df[(df["Returned"] == True) & (df["Customer_Age"]<30)]

          Date    Product  Sales  Customer_Age  Customer_Rating  Returned
0   2020-01-08  Product B     87            55                4     False
1   2020-01-20  Product B      9            53                1     False
2   2020-02-19  Product C     12            37                3     False
3   2020-03-03  Product A     81            35                5     False
4   2020-03-13  Product C     62            45                2      True
5   2020-04-15  Product A     88            58                2     False
6   2020-04-18  Product C     85            43                3     False
7   2020-04-20  Product C     62            46                4     False
8   2020-06-03  Product B     77            28                4      True
9   2020-06-05  Product A     33            45                4     False
10  2020-07-09  Product C     63            66                5      True
11  2020-08-09  Product B     36            61                5     False
12  2020-08-13  Product B     44            20                2     False
13  2020-08-28  Product A     70            65                2      True
14  2020-09-23  Product A     54            19                1     False

In [27]:
#Task 2
#Выбрать продажи для определенной даты
df.loc[df["Date"] == '2020-04-15']

#Выбрать данные по диапазону индексов и определенным колонкам
df.loc[5:10, ['Product','Sales']]

#Изменить данные для определенного условия:
df.loc[df["Customer_Rating"] == 1, "Returned"] = True
print(df[df["Customer_Rating"] == 1])

          Date    Product  Sales  Customer_Age  Customer_Rating  Returned
1   2020-01-20  Product B      9            53                1      True
14  2020-09-23  Product A     54            19                1      True

In [29]:
#Task 3
#Группировка по продукту и подсчет среднего возраста покупателей
df.groupby("Product").mean("Customer_Age")

#Группировка по рейтингу покупателя и подсчет общей суммы продаж
df.groupby("Customer_Rating").sum('Sales')

                 Sales  Customer_Age  Returned
Customer_Rating
1                   63            72         2
2                  264           188         2
3                   97            80         0
4                  259           174         1
5                  180           162         1